### PR TITLE
FIX: incorrect variable name

### PR DESCRIPTION
**Pull request by barbequesauce**
FIX: incorrect variable name (#2035) Thank you @ajslater!

### CODE REVIEW

**Comment by ajslater** [comment]
This PR needs to also change
https://github.com/evilhero/mylar/pull/2420/files#diff-d13ba27a96559d3d22b637a3da042c04L2327
to remove the unused and illegal `ssl` parameter.

And the button.... gets a little further. There's more to do after that. The button returns a 404 from its get. Will look into this as well.

**Comment by ajslater** [comment]
https://server/mylar/testtorznab?name=Jackett&host=http%3A%2F%2Fjackett%3A9117%2Fjackett%2Fapi%2Fv2.0%2Findexers%2Fall%2Fresults%2Ftorznab&apikey=MYAPIKEY

Returns 404, because the testtorznab endpoint doesn't even exist in webserve.py

Probably can copy/paste some testnewznab code and make one.

**Comment by barbequesauce** [comment]
I stared at it last time around for three hours and didnt catch the incorrect variable, so I'm just happy about finding that :)

**Comment by barbequesauce** [comment]
Subsumed

**Pull request closed without merging**
