### PR TITLE
Added clearlogs getLogs to api.

### PR DESCRIPTION
**Pull request by Hellowlol**

### CODE REVIEW

**Comment by evilhero** [comment]
PR was sent to wrong branch (can't commit to Master). 

I can manually put it into the development branch, so you don't have to do another PR and push it out. But it's up to you...

**Comment by Hellowlol** [comment]
Yeah, that would have been fine. It's a small change

**Comment by Hellowlol** [comment]
Thanks!

**Comment by Hellowlol** [comment]
Im not sure why mylar does it this way, that list must be huge and after a reboot there are no logs. It would be better to actually read the log?

**Comment by evilhero** [comment]
I don't know why I just saw this now, but I'm not 100% sure I fully understand what you're saying.  

The loglist variable isn't being populated or its populating too much?

I've noticed before that the log only loads from the log lines from startup -which it should load the entire file(s) ..not sure what it's doing exactly as I haven't touched the logging in a very long time.

**Comment by Hellowlol** [comment]
None of them. I just think it would be better to actually read the log instead of a in memory list. Right know you can't debug Mylar without opening the log in a editor. (Say you need to restart after changing some settings)

**Pull request closed without merging**
