### PR TITLE
Added some to the api: findComic, addComic, downloadIssue

### PR DESCRIPTION
**Pull request by Hellowlol**

### CODE REVIEW

**Comment by evilhero** [comment]
Sorry for delay in this, I'm planning on pushing this into development later tonight - some other items kind of mangled the schedule up abit.

**Comment by Hellowlol** [comment]
No worries. I have let the ppl requesting Mylar support know that they had to use my pr until it got merged

**Comment by evilhero** [comment]
Pushed it to Development a few minutes ago, as well as into Master (it was just in the mix in order to get everything up to the same level).

Thanks again for all the contributions to the API - you're saving me doing a ton of extra work that would take me forever to probably just figure out since I don't use the API as much as something like your app would :)

Cheers!

**Comment by Hellowlol** [comment]
Thanks for merging this so quickly. Is issueid unique for all comics? I sure hope so..

**Comment by evilhero** [comment]
Yep, issueid is unique so it shouldn't hit any snags from that aspect ;l

**Pull request closed without merging**
