### PR TITLE
Hellowlol patch 1

### PR DESCRIPTION
**Pull request by Hellowlol**

### CODE REVIEW

**Comment by evilhero** [comment]
I don't really want to cherry-pick this apart, but I don't want to merge this into the master branch until it's been in the development branch. 

Can you redo the PR for the development branch and I can merge it (I didn't notice it wasn't on the dev until just moments ago as I was viewing the PR's on my phone)?

**Comment by Hellowlol** [comment]
Hi! Master was ahead of development do I just assumed it was a inactive branch. I'll make a pr to development

**Comment by Hellowlol** [comment]
@evilhero  Just to be clear your want me to branch of development do my stuff then make a pr to development?

**Comment by evilhero** [comment]
Yes, the commits ahead got screwed up awhile ago and it's still pointing to some already merged commits thinking they're not committed, but development is where all PRs should point to initially. 

I'm holding off on pushing my updates to development until I can get your PR as I know some code got changed (in the init and importer mainly) so I want to do a local merge of your PR to test before I push it live :) 

Sorry for asking for another PR, it's all greatly appreciated - I just don't want to break things royally (tends to happen with git and me a few times/year at least)

**Comment by Hellowlol** [comment]
Np, ill do it tomorrow

**Pull request closed without merging**
