### PR TITLE
Add imageurl for notifiers + Typo in log message

### PR DESCRIPTION
**Pull request by Bart274**
Small irrelevant fix of a typo in the log messages.

Would it be possible to add covers into Mylar? So when browsing the issues of a comic, you can see the cover of each issue in the list and when receiving notifications of processed issues, these cover can be sent as well?

### CODE REVIEW

**Comment by BRTPOB** [comment]
I think the merge needs to happen. As for the covers, that's not a bad idea.

**Comment by Bart274** [comment]
I’ve looked into it and it was easy to add the imageurl to the notifiers.
I only updated the Telegram notifier because I know that one but the same could be added for others. I’ve tested it locally and it works just fine.
CCBB250E-EE77-40CA-9FC8-D208D430C3F2

**Comment by Bart274** [comment]
@BRTPOB now this PR makes more sense to be merged :)

**Comment by barbequesauce** [comment]
Good stuff. Can you also make the same changes in the [python3 repo](https://github.com/mylar3/mylar3 )? We are nearing a freeze on this one...

**Comment by Bart274** [comment]
@barbequesauce I didn't knew there was a new repo, I just thought there was a new branch for python3.
Have you guys considered starting a discord server for easier communication?

**Comment by BRTPOB** [comment]
We use IRC, which is where most of the magic happens.

**Comment by Bart274** [comment]
Isn't Discord easier to have multiple channels with their own privacy settings, with bot to notify about git changes etc,...?

**Comment by Bart274** [comment]
Anyway @BRTPOB , the PR in the python3 repo has been made. https://github.com/mylar3/mylar3/pull/53

I cleaned up the code a bit

**Comment by BRTPOB** [comment]
uhh Discord is IRC just with voice chat. Literally the same thing.

That said, @evilhero does the merges. Not me. I'm QA.

**Comment by barbequesauce** [comment]
Thanks @Bart274, good stuff.

Our IRC channel has a bot wired into GitHub and the forums too - we're old-school...

**Comment by Bart274** [comment]
I need to check it our then, anyone knows a good iOS client?

I’m gonna add a fallback to the default message in case sending the photo fails (which appears to happen sometimes even with the right url)

**Comment by BRTPOB** [comment]
We all use The Lounge. Web based client, works everywhere.

**Comment by barbequesauce** [comment]
If you hate node.js, there's also Limechat...

**Comment by Bart274** [comment]
So you guys run your own client on your servers and then connect to it on your mobile using your browser?

**Comment by barbequesauce** [comment]
Exactly.

**Comment by Bart274** [comment]
58168CAB-86DB-4EFB-BE88-EB55FB5E608D
Fallback works fine

**Comment by BRTPOB** [comment]
Dude, this is awesome (first off, and I can't wait to see it inside of Mylar (a); you're also making me want to get a Telegram bot setup so I can see that kind of stuff going forward (b).

**Comment by evilhero** [comment]
Nice job! This is now in development as of 563439a

The only caveat I see in all of this is two-fold:
1 - some users might not want images being sent, in which case each notifier should have a togglebox to enable/disable the ability to send images with the notifs.
2 - aside from telegram, most of the services don't allow url redirection for downloading images - which means that it would have to be a local file being sent to the provider's API. Which isn't a problem to extract the cover after post-processing, and send that. That allows for visual verification of what was downloaded is actually what was downloaded, as well as not hitting CV with numerous image requests outside of their API (not a problem now, but if the entire Mylar user base is doing it on a busy day, it might get dicey).

We'll have support for the other providers probably later this week as we can get around to it (Slack & Pushover first since those are the ones that we use mainly), but regardless of the final implementation going forward, this is definitely a nice addition!

**Comment by Bart274** [comment]
@evilhero glad you like it. Telegram support for both local and remote files to be sent.
If you have the file itself, it can be sent instead.

**Comment by barbequesauce** [comment]
@Bart274 can you close this please

**Pull request closed without merging**
