### PR TITLE
OPDS enhancements

### PR DESCRIPTION
**Pull request by casret**
I fixed up the opds readlist, and implemented a workflow that makes sense to me, where if you download the comic through the feed it will mark it as Read in the reading list, and won't display it in the feed.  I don't have the android reader, so tell me if it messes up something in that workflow.

### CODE REVIEW

**Comment by casret** [comment]
The bug was on line 605.  fileloc was undefined

**Comment by barbequesauce** [comment]
Got it - thanks.

**Comment by evilhero** [comment]
Looks good - will push to dev later today. Thanks for the PR!

**Comment by evilhero** [comment]
Now in development - thanks for the PR! :)

**Comment by glberen** [comment]
Thank you as well. This, I think, fixed the opse reading list in chunky reader for me. The only way it functions differently from the normal lists is that you have to download the issue instead of just "streaming" it from the server. That might be a cool addition later if you're in the mood for enhancement. Thank you very much for this!

**Comment by casret** [comment]
@glberen The Ubooquity steaming extension (which is what I assume you are using) is a bit tricky to implement on top of mylar since it requires reading into the actual archives and unrar on python is a PITA.  I'll add it to my TODO list for the [OPDS server](https://github.com/casret/rust_opds) that I'm writing, but I don't have a timeline for even the alpha of that.

**Comment by barbequesauce** [comment]
On a side note, ChunkyTNG will have a desktop server engine with the page streaming extension built in...

**Comment by glberen** [comment]
Very cool about ChunkyTNG. Didn't even know that was thing. Yeah - I'm using ubooquity (I wasn't thinking when I commented that it was a completely different engine...duh!). Ubooquity works well, but makes keeping track of where you are in a series difficult, unless you download all the books, then Chunky will handle the read/unread status. That's why I was keen on the mylar OPDS, since I can manage the reading list there pretty easy without filling up the iPad.

**Comment by casret** [comment]
@glberen FYI My OPDS server supports the streaming extension now, and will mark the issue as read as soon as you stream the last page.  Working great, thanks for the suggestion.

**Comment by glberen** [comment]
That's awesome! Thanks for adding that functionality.

**Pull request closed without merging**
