### PR TITLE
Send snatched_name in Telegram messages on snatch

### PR DESCRIPTION
**Pull request by Bart274**
The current snatch message is always just `Issue snatched!`

### CODE REVIEW

**Comment by Bart274** [comment]
Original notifications:
Screenshot from 2019-07-09 15-01-07

Notifications after change:
Screenshot from 2019-07-09 15-01-12

**Comment by evilhero** [comment]
Will merge this sometime soon - my time during the summer is very, very thin. I get to sign on, and check some things, but don't get much time at all to code (it's basically akin to having 8 weeks of vacation from a job, but nowhere near as enjoyable).

I'll merge this when I get a chance - just wanted to let you know that the PR is appreciated and it will get merged at some point.

Cheers,

**Comment by Bart274** [comment]
Hi @evilhero 

Take your time to validate this PR :-)
It's a very small change, so it shouldn't be hard to check it, but it's not an urgent 'issue'. It's not a bugfix or anything so it doesn't matter if you a little bit more time to add it. :-)

**Comment by evilhero** [comment]
All good in development now - thanks for the PR!

**Pull request closed without merging**
