### PR TITLE
Fix for visual snag with checkboxes

### PR DESCRIPTION
**Pull request by WedgeSparda**
Updated version of my previous PR [https://github.com/evilhero/mylar/pull/1435](url), no merge conflicts this time.

### CODE REVIEW

**Comment by evilhero** [comment]
I can see the changes work in IE/Edge, but in Chrome the display looks off like it did originally. Tried manipulating the margins to compensate, but still can't get it to line up in chrome properly for some reason.

**Comment by WedgeSparda** [comment]
That's weird. I tested on Chrome. Can you delete cache and see if it changes?

**Comment by evilhero** [comment]
Yeah that was me being stupid - I have like 4 different browsers, and thought I cleared the cache from my canary chrome...apparently I missed that one ;)

Now in development - thanks again for the PR's!

**Comment by WedgeSparda** [comment]
Thanks to you. I'll close the PR.

**Pull request closed without merging**
