### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by csavage5**
- labeled sections with proper headers
- added link to API key
- clarified code input in "Usage" section
- cleaned up "Usage" section
- cleaned up "Renaming" section
- created a section for "Screenshots"

### CODE REVIEW

**Comment by evilhero** [comment]
While I appreciate the effort put forth, the README file needs to get updated entirely as there are alot of new things present, as well as items not needed anymore.  That being said, this is probably a good start in that direction. 

So first, and before anything else - thanks much for the PR. 

Now, the PR is against the master branch and not the development branch so that will have to be corrected prior to any merge occurring. 

Also, there is no need to label something as a *BUG* within the README - especially one that doesn't exist in any current build. The settings /reboot problem was taken care of close to 2 yrs ago, but I get that people just assume stuff is still the same and then word of mouth travels.

So remove the BUG indication, put the PR against development and this will get merged pending any insight from anyone else.

Cheers,

**Comment by csavage5** [comment]
I've removed the [BUG] indication and changed the branch from "master" to "development".

**Comment by evilhero** [comment]
Ok, thanks for that. I should have been more clear - there's no need to restart Mylar after saving the configuration anymore (unless it's a port change or something - but the warning is present within the config for that). So that entire line can be removed.

Also your PR has way too many commits - can't be merged as it is like that. You have to do the PR for just the change you're doing (not the commit history of the branch it looks like).

**Comment by csavage5** [comment]
Ah, alright. I think the commits are like that since I branched off of the master and I'm merging into the development branch. I'll branch off the development branch, re-do the changes, and submit another pull request.

**Comment by evilhero** [comment]
Closing this as the PR against dev is in the list

**Pull request closed without merging**
