### PR TITLE
Development

### PR DESCRIPTION
**Pull request by DarkSir23**
Initial (simple) uTorrent support.  Queues the download and sets the label.  Would like to modify the config setup in the near future, but would like to discuss it before I do.

### CODE REVIEW

**Comment by gokuu** [comment]
@DarkSir23 , I've installed your fork on a debian machine, using utorrent server, and even though I can add the files to download, It doesn't set the label.

What I find strange is that on my nginx logs, that is in front of the web UI, I get duplicate entries for each request:

```
127.0.0.1 - - [06/May/2016:19:12:57 +0100] "GET /gui/token.html HTTP/1.1" 401 0 "-" "Python-urllib/2.7"
127.0.0.1 - user [06/May/2016:19:12:57 +0100] "GET /gui/token.html HTTP/1.1" 200 121 "-" "Python-urllib/2.7"
127.0.0.1 - - [06/May/2016:19:12:57 +0100] "GET /gui/?token=SyFY9KpHBM0gs5vhrnmwDWiHJwTbw7gkAAAAAG4lYzEAAAAAl6mqA6neLFcAAAAA&action=add-url&s=https%3A%2F%2Ftorcache.net%2Ftorrent%2F1D88AB7245F0ABE42481E83984A723E8E1360A85.torrent HTTP/1.1" 401 0 "-" "Python-urllib/2.7"
127.0.0.1 - user [06/May/2016:19:12:57 +0100] "GET /gui/?token=SyFY9KpHBM0gs5vhrnmwDWiHJwTbw7gkAAAAAG4lYzEAAAAAl6mqA6neLFcAAAAA&action=add-url&s=https%3A%2F%2Ftorcache.net%2Ftorrent%2F1D88AB7245F0ABE42481E83984A723E8E1360A85.torrent HTTP/1.1" 200 16 "-" "Python-urllib/2.7"
127.0.0.1 - - [06/May/2016:19:12:57 +0100] "GET /gui/token.html HTTP/1.1" 401 0 "-" "Python-urllib/2.7"
127.0.0.1 - user [06/May/2016:19:12:57 +0100] "GET /gui/token.html HTTP/1.1" 200 121 "-" "Python-urllib/2.7"
127.0.0.1 - - [06/May/2016:19:12:57 +0100] "GET /gui/?token=oocjiePQ-r_DxB41e5uL1rCdTcgMbTzOAAAAAOaOsbEAAAAAXmR0r6neLFcAAAAA&action=setprops&hash=1D88AB7245F0ABE42481E83984A723E8E1360A85&s=label&v=comics HTTP/1.1" 401 0 "-" "Python-urllib/2.7"
127.0.0.1 - user [06/May/2016:19:12:57 +0100] "GET /gui/?token=oocjiePQ-r_DxB41e5uL1rCdTcgMbTzOAAAAAOaOsbEAAAAAXmR0r6neLFcAAAAA&action=setprops&hash=1D88AB7245F0ABE42481E83984A723E8E1360A85&s=label&v=comics HTTP/1.1" 200 16 "-" "Python-urllib/2.7"
```

The first one always fails, and can't event identify the user under which Mylar is running. I'm using the same setup with Sonarr and CouchPotato without a problem. Any clue?

**Comment by DarkSir23** [comment]
Please re-pull and try again, I spotted a glitch. Please let me know, I've only tested on Windows, but can test further on Linux, if need be :)

**Comment by gokuu** [comment]
It's working now, thanks! Keep up the good work 👍

**Comment by evilhero** [comment]
This is great!

I've just merged this into my local build now and working through integration with some other items (mainly rtorrrent like we had discussed and you allowed for in the PR). 

One thing I happened to notice is that Mylar already has downloaded the .torrent file (as Mylar stores it in the cache), but then the addurl is being called to add it directly via the torrent url. Would it not work if in lieu of:
```
uTorrentClient.add_url(link)
```
it was:
```
uTorrentClient.add_file(filepath)
```
If the add_file was used, it also has the added plus of returning a hashref indicating if an error has occured. Keep in mind I have no idea if this is even a valid option since I don't use uTorrent at all, but it would seem it would work the same and save time since it doesn't have to call the torrent download url again, wait for the time-wait on the torcache site(?).

**Comment by DarkSir23** [comment]
You're probably right.  I'll take a look at it tomorrow, and see how well it works :)

**Comment by evilhero** [comment]
Sounds good - I'll hold off on merging this into development until you have a chance to run it out. 

I didn't evem realize that I had already included a utorrent process file within mylar - something to check out if any further type of actions might be required, or even just for comparison.

**Comment by DarkSir23** [comment]
Actually, if you don't mind, go ahead with it as it is.  uTorrent DOES support add-file, but it looks like I need to send it POST data rather than a GET.  This will work in the meantime, and I'll do a bit of testing to see what all I need to wrap into the post form.

**Comment by DarkSir23** [comment]
I made some progress with using add-file, but keep hitting an decoding error trying to wrap the file contents in POST data. I may need to try to switch everything over to use the request library instead of urllib2.

**Comment by evilhero** [comment]
That's probably better - the requests module already lives in lib.requests so just use that instead of having to add another version of requests ;)

I just merged the PR into development with the changes I made to the PR. Mainly it was just the addition of rTorrent into the GUI, but I also shifted around the local watchdir/seedbox watchdir options so they all fall under the same option in the GUI. In doing so, I also added the template for the addition of Transmission in the future.

In case I haven't said it recently, thanks again for the PR and all the work you've done for this!

**Pull request merged**
