### PR TITLE
add telegram notifier

### PR DESCRIPTION
**Pull request by Bart274**
This *should* allow the Telegram notifier to be used.
I based my code on the implementation of the code used in Headphones for Telegram and the implementation of the Pushbullet notifier in this program.
This should resolve my own Feature Request: https://github.com/evilhero/mylar/issues/1426

### CODE REVIEW

**Comment by Bart274** [comment]
No problem, I thought this wouldn't be a priority for you so I might lend a hand :)

**Comment by evilhero** [comment]
Sorry, I didn't even realize - you need to put the PR against the development branch. 

I can't currently merge it into master as it would cause alot of problems given how much difference in code there is between the master and development branches.

**Comment by Bart274** [comment]
Ok, I'll check tomorrow ?

**Comment by Bart274** [comment]
@evilhero when I changed the base branch of the PR, it imported all the commits that are different between master and development as well, so I deleted my branch and closed this PR in favor of my new PR: https://github.com/evilhero/mylar/pull/1447

**Pull request closed without merging**
