### PR TITLE
Add Deluge for Torrent downloads

### PR DESCRIPTION
**Pull request by Undeadhunter**
Added Deluge as an option for downloading torrents. 

I'm making use of https://github.com/JohnDoee/deluge-client for the RPC calls to the daemon (not the webUI) since it's easier than rewriting from scratch.. 

The deluge.py is bare minimum, (just connect and load_torrent). 
I'm not completely clear what the other functions are for currently, but if it can be made a bit more clear I'm off course able to expand those functions.

### CODE REVIEW

**Comment by evilhero** [comment]
Well this will be a nice early Christmas present for some users ;)

I know this has been requested alot, and from the PR it all looks fine (I don't have a client to test it on atm, so I'm going on blind faith here) - I'll merge the PR later today when I can get back to a machine to do the merge and just do some quick startup tests to make sure nothing breaks on the merge. 

Thanks for the PR and doing the leg work to get this functional within Mylar, as I'm sure there are users out there awaiting this exact PR.

Cheers!

**Comment by Undeadhunter** [comment]
Since I was tired of waiting myself, I just decided to do it myself! That's the great thing about open source ;)

**Comment by evilhero** [comment]
Ok, I fired up a deluge client and did some quick tests - aside from getting a label not created error it worked perfectly fine. So in testing it, I actually amended the label check portion too - so now when it tries to create a label for a torrent, if it fails it will attempt to create the label and then re-set the label again before sending a fail response.

Other than that one error which was obviously due to my lack of configuration, nice job - and thanks for the PR!

As far as the other functions, get_torrent and find_torrent (at least in rutorrent rpc) are both utilized by Mylar to ensure the torrent has loaded successfully. A future commit coming, will have an option for an automated 'snatcher' (no idea wtf to name it, but yeah) - which will monitor the downloading of a given torrent (by hash ID) and when it's completed, it will download the torrent from the client to the local machine that Mylar is running on. This is especially useful if one is running their torrent client on a seedbox or external box and have to continually download files from the box for Mylar to post-process. Again, not for everyone - but I have had it running on my local machine for the past week or so and it works well with rutorrent so as long as the get_torrent and find_torrent options are available for the given client, this would work as well too. Based on this, it would be also possible for Mylar to monitor torrent downloads for completion, ratio, seed time, etc...

**Comment by Undeadhunter** [comment]
I'll take a look to add those functions

Do you save the torrentid/hash somewhere? 

For the 2 functions:
find_torrent() will check the client for an existing torrent with the same hash as the file ? What's best way to get hash from torrent? Use libtorrent.get_info?
and get_torrent() will get the stats about the torrent? What would you be expecting?

From test.py I assume: 
'hash'
'name'
'label'
'folder'
'completed'
'files'
'upload_total'
'download_total'
'ratio'
'total_filesize'
'time_started'

**Comment by evilhero** [comment]
The Torrent hash will be available for saving in either the next commit or shortly thereafter (I'm pushing out some small fixes atm, so whenever I finish those little ones). It's currently being saved in the snatched table of the db under the Hash field upon successful snatch/send of the torrent.

You don't have to get the hash from the torrent, as it's saved into the db upon snatch - so it should be fairly simple to just do a find_torrent to verify that the torrent exists still in the client, and then torrent_info (if it follows the libtorrent api, not sure if it's built into the deluge script) to retrieve the information about the torrent itself by passing it the hash. And yes, that information that's retrieved should be (hopefully) what is returned - at the very minimum, the name of the torrent (filename), the folder, completed status, and filesize.

Hopefully that helps somewhat, if you need any more information or just have a concern/question feel free to shoot me a message and

**Comment by Undeadhunter** [comment]
Closing since it's been added in dev already

**Pull request closed without merging**
