### PR TITLE
IMP: Added new basic email notifier

### PR DESCRIPTION
**Pull request by Arathen**
Added a basic email notifier. Works with unencrypted, SSL and TLS SMTP. Tested (including deliberate misconfigurations) with Gmail, Outlook/Hotmail, Mailgun and my own Postfix server.

This is the first commit to establish the base functionality, but there is more that i'm planning to add like multiple email recipients and perhaps more notification detail.

Also @evilhero how do you feel about moving Notifications to a new config tab all of their own? The list is getting pretty long and easily scrolls off the bottom of my screen, and the layout of the Advanced settings tab is a little lopsided as a result. I think theres enough of them, and the functionality unique enough, that they warrant their own tab. Im happy to take a crack at doing this if you like?

My python and javascript skills are still in their very early days so there may be bugs with this still. I'm happy for you to tag me in any bug reports and i'll try to clean up after myself.

### CODE REVIEW

**Comment by evilhero** [comment]
I waited too long to try and merge this, and now there's too many differences in amongst the webserve.py file to allow for the patch to import without errors.

Can you redo the PR against the latest development commit and then I can merge things properly ? Sorry for that - no excuse for waiting this long to merge other than was too busy with other items / life.

**Comment by Arathen** [comment]
Done, I think. Let me know if there are any problems.

**Comment by evilhero** [comment]
Actually you need to do the PR so only the changed files are included (as per your original PR)- I can't merge stuff that's already been merged (all the commits would mess up things). You just needed to update your local branch, then do the PR against that local branch so that only the changed files in your PR should be tagged in the PR (if that makes sense).

**Comment by Arathen** [comment]
Closing.

**Pull request closed without merging**
