### PR TITLE
implement torznab test

### PR DESCRIPTION
**Pull request by ajslater**
torznab test was only partially implemented on the front end and never implemented on the back end, which of course made the test button fail as noticed in #2035

This PR supersedes https://github.com/evilhero/mylar/pull/2419 and https://github.com/evilhero/mylar/pull/2420

The partial front end torznab test implementation did not expose a Verify SSL button, but this PR does implement one on the front and back end.

cc: @barbequesauce

### CODE REVIEW

**Comment by barbequesauce** [comment]
Looks good from here - but wrong branch... can you resubmit to development (and/or python3-dev)

**Comment by ajslater** [comment]
Thanks, my bad. Rebased.

**Comment by barbequesauce** [comment]
Ooofff looks like you're rebasing master over development... wayyyy too many commits there. Might want to just close it and redo the push against development

**Comment by ajslater** [comment]
woooops. yeah i'll just nuke it and do this over.

**Pull request closed without merging**
