### PR TITLE
Support for transmission

### LINKED ISSUE #606: Feature request: Transmission for torrents
I run Mylar on a synology NAS and absolutely love it! But one feature I think would be great would be the ability to send torrents directly to transmission rather than use a watch folder. I'm not sure how the code works, but it's a feature that's available in sickbeard, headphones, couch potato etc. any chance of migrating this feature to Mylar? It would be much appreciated!

### LINKED ISSUE #1297: Make transmission possible
I was wondering if it's possible to make transmission available. I know you can use transmission by making use of the watchdir but I don't really see this as the prefered way to go.

Looking at the gui code I saw that the transmission part was being commented out. Is there a reason for this? Is this something that should be done in the feature or was previously tried but didn't work?

### PR DESCRIPTION
**Pull request by tresni**
Fixes #1297
Fixes #606 

six is a dependency of transmissionrpc.  Tried to do it similar to how utorrent and rtorrent are setup.

### CODE REVIEW

**Comment by evilhero** [comment]
Wow that's awesome! I know a lot of users have been requesting this feature, but I've been unable to get around to it - so you definitely made some people happy :) 

I'll try and merge this into the dev branch later tonight so it  can be tested and I'll report back on anything that might cause problems going forward. 

Thanks again for taking the time to do the PR!

**Comment by Neo00724** [comment]
Can't wait !!!

**Comment by knightabe** [comment]
Any update on this getting merged into development/dev branch? I'd be happy to rebuild my docker image against it for testing.

**Comment by evilhero** [comment]
Yep, once I can push out the next commit into development, I'll be doing this merge. A few items have changed so I'll have to manually patch some items, but it's not going to be a show stopper. Hope to get the next dev up today at some point, then will be followed by this PR shortly.

**Comment by evilhero** [comment]
Ok, it's up and live for everyone to test ;) 

I don't run transmission, so I just pushed it out without any real testing aside from startup. 

The only thing I did have to change was the module paths that are called within some of the modules - for some reason, it wouldn't start up unless I changed them from 'transmissionrpc.constants' to just 'constants' (as an example)...not sure if it might have to be changed again, but that's how I got it working so had to push it out as such.

Thanks again @tresni for the PR - hope the slight change(s) I did still allow things to work?

**Comment by tresni** [comment]
Interesting.. Wonder why I didn't see that myself.  Traveling so I'll retest when I get back home and let you know!

**Comment by rbm-aalsaleh** [comment]
I'm currently unable to test this. I find myself without a torrent source. Working on that. I'll try to report back when I can.

**Comment by knightabe** [comment]
I'm currently unable to test this. Find myself without a torrent source. I'm working on that and will try to report back when I can.

**Comment by evilhero** [comment]
Going to close this - this merged into development, and also the lib-changes PR as well, so any further problems with transmission should be on it's own issue.

Thanks again for the all the PR's @tresni !!

**Pull request closed without merging**
