### PR TITLE
Minor fixes for search queue/post-processing locks

### PR DESCRIPTION
**Pull request by ivtechboyinpa**
242df9a - Windows has a 260 character limit on directory paths. The win32api module was installed and imported to allow for computers running Windows OS to bypass that limitation, as ComicRN was not able to move or rename files with a long file path.

### CODE REVIEW

**Comment by ivtechboyinpa** [comment]
Encapsulated a logger line in a try-except block, which would cause the search queue to error out and stay locked until the program restarts.

**Comment by ivtechboyinpa** [comment]
94d7399 - Was trying to download a Green Lantern comic, which was grabbing from DDL. Issue volume was being found as "v01002" because the comic was labeled "v01.002" for volume #1, issue #2. Added a check for periods in volume parsing to account for this.

4d50b59 - Was trying to download a Batman comic, which was also grabbing from DDL. It found the comics but failed them and tried to download a Justice League pack instead. When I tried to manually fail the comic it would throw an error for the "sandwich" variable, and that's because it was never being set to due to not meeting any of the conditions. Therefore I added a try-except to catch when sandwich is not set to exit the running thread and NOT lock up the search queue.

**Comment by ivtechboyinpa** [comment]
c02c70c - Found on trying to download an X-Men comic, the issue wasn't being parsed correctly because there was a period in :".2013" and hence was not picking up the actual volume number. I changed the parameters for using str.split() to be more exclusive.

Say in the case of "v01.002"; the parameters have to match both "v" and "." in the string to parse the first part (v01).

**Comment by evilhero** [comment]
All pushed into development as of 07750a3. I didn't test any of these, so I'm going to rely on the userbase to tell me/us if there are any problems going forward.  The file parser modification might be the only one that I can forsee a possible problem with just because the parser is used by a bunch of different modules - but again, initial tests seem ok on my end.

Also, for future reference  - please try to keep the patches independent of each other. For tracking purposes (and merging), having individual PRs make things much easier on our side.

Cheers for the PR's :)

**Comment by ivtechboyinpa** [comment]
> Also, for future reference - please try to keep the patches independent of each other. For tracking purposes (and merging), having individual PRs make things much easier on our side.
> 
> Cheers for the PR's :)

Gotcha. I actually had intended to submit separate PRs, but when I added commits they all automatically populated here. How would I go about making sure they get submitted as independent PRs?

And no problem, glad for the work you have done and happy to help out!

**Pull request closed without merging**
